#!/usr/bin/env bash
# Displays numbers from 1 to 100 display Fizzbiz when number is multiple by 3 and 5, Fizz when the number is multiple of 3, Displays Buzz when the number is a multiple of 5
for i in {1..100}
do
if [ $((i % 5)) -eq 0 ] && [ $((i % 3)) -eq 0 ]
then
echo "FizzBuzz"
elif [ $((i % 5)) -eq 0 ]
then
echo "Buzz"
elif [ $((i % 3)) -eq 0 ]
then
echo "Fizz"
else
echo "$i"
fi
done
