#!/usr/bin/env bash
#display best school 10 times but bad luck on 4th loop good luck on 8th loop
i =1
while ["$i" -le 10]
do
if ["$i" -eq 4]
then 
echo "bad luck"
elif ["$i" -eq 8]
then
echo "good luck"
else
echo "Best school"

fi

i=$((i+1))
	done
