#!/usr/bin/env bash
#printing 1 to 20 but print bad luck from china after printing 4, bad luck from japan after 9 and bad luck from italy after 17
i=1
while [ "$i" -le 20 ]
do
case $i in
4)
echo "4"
echo "bad luck from China"
;;
9)
echo "9"
echo "bad luck from Japan"
;;
17)
echo "17"
echo "bad luck from Italy"
;;
*)
echo "$i"
;;
esac
i=$(( i + 1 ))
done
