#!/usr/bin/env bash
#this script displays I am invncible when you try to terninate it from another file script
while true;
do
echo "To infinity and beyond"
sleep 2
trap 'echo "I am invincible!!!"' SIGTERM
done
